INSERT INTO studios (
    nom, 
    description, 
    adresse, 
    latitude, 
    longitude, 
    prix_par_heure, 
    equipements, 
    photo_url, 
    proprietaire_id, 
    statut, 
    code_postal
) VALUES 
(
    'Sonic Lab Brussels',
    'Studio d''enregistrement professionnel avec acoustique parfaite',
    'Rue de la Régence 67',
    50.8419176,
    4.3188224,
    45.00,
    '{"mixing_console": "SSL 4000", "microphones": ["Neumann U87", "AKG C414"], "monitors": ["Yamaha NS10", "Genelec 8050B"]}',
    'https://example.com/photos/sonic-lab.jpg',
    1,
    'validé',
    1000
),
(
    'Melody House',
    'Petit studio chaleureux idéal pour les artistes indépendants',
    'Avenue Louise 143',
    50.8350,
    4.3547,
    35.00,
    '{"mixing_console": "Behringer X32", "microphones": ["Shure SM58", "Rode NT1"], "instruments": ["Piano droit", "Guitare acoustique"]}',
    'https://example.com/photos/melody-house.jpg',
    2,
    'validé',
    1050
),
(
    'Beat Factory',
    'Studio spécialisé dans la production hip-hop et électro',
    'Chaussée de Wavre 354',
    50.8392,
    4.3846,
    55.00,
    '{"DAW": "Ableton Live", "synthesizers": ["Moog Sub 37", "Roland TR-8"], "monitors": ["KRK Rokit 8"]}',
    'https://example.com/photos/beat-factory.jpg',
    1,
    'validé',
    1040
),
(
    'Classic Vibes Studio',
    'Espace d''enregistrement vintage avec équipement analogique',
    'Rue Belliard 202',
    50.8428,
    4.3751,
    65.00,
    '{"mixing_console": "Neve 1073", "tape_machine": "Studer A800", "microphones": ["Telefunken ELA M 251", "RCA 44"]}',
    'https://example.com/photos/classic-vibes.jpg',
    2,
    'validé',
    1040
),
(
    'The Sound Cave',
    'Studio souterrain avec isolation acoustique exceptionnelle',
    'Rue du Midi 33',
    50.8461,
    4.3452,
    40.00,
    '{"mixing_console": "Allen & Heath SQ-7", "drums": "Pearl Masters", "amplifiers": ["Fender Twin", "Marshall JCM800"]}',
    'https://example.com/photos/sound-cave.jpg',
    1,
    'validé',
    1000
),
(
    'Uptown Records',
    'Studio moderne avec vue panoramique sur Bruxelles',
    'Avenue Franklin Roosevelt 50',
    50.8150,
    4.3814,
    75.00,
    '{"mixing_console": "API 1608", "monitoring": "Full Dolby Atmos Setup", "microphones": ["DPA 4006", "Schoeps CMC6"]}',
    'https://example.com/photos/uptown-records.jpg',
    2,
    'validé',
    1050
),
(
    'Green Room Studio',
    'Studio écologique alimenté à l''énergie solaire',
    'Rue Gray 171',
    50.8379,
    4.3705,
    45.00,
    '{"mixing_console": "Soundcraft Vi1000", "instruments": ["Gibson Les Paul", "Fender Jazz Bass"], "plugins": "Waves Complete"}',
    'https://example.com/photos/green-room.jpg',
    1,
    'validé',
    1040
),
(
    'NoLimit Studio',
    'Grand espace polyvalent pour enregistrement et vidéo',
    'Boulevard du Souverain 165',
    50.8161,
    4.4089,
    85.00,
    '{"mixing_console": "Avid S6", "video_equipment": "RED Camera", "microphones": ["Sennheiser MKH 8040", "Schoeps CMC6"]}',
    'https://example.com/photos/nolimit.jpg',
    2,
    'validé',
    1160
),
(
    'Urban Sound Lab',
    'Studio compact au cœur de Bruxelles',
    'Rue Antoine Dansaert 202',
    50.8502,
    4.3461,
    30.00,
    '{"mixing_console": "Presonus StudioLive", "drum_machine": "Akai MPC X", "synthesizers": "Nord Lead 4"}',
    'https://example.com/photos/urban-sound.jpg',
    1,
    'validé',
    1000
),
(
    'Echo Chamber',
    'Studio avec chambre de réverbération naturelle',
    'Rue de la Loi 155',
    50.8466,
    4.3703,
    50.00,
    '{"mixing_console": "Midas M32", "reverb_chamber": "Natural Stone Room", "microphones": ["AKG C414", "Royer R-121"]}',
    'https://example.com/photos/echo-chamber.jpg',
    2,
    'validé',
    1040
);